######################################################################
# Automatically generated by qmake (3.0) Tue Nov 17 12:11:59 2015
######################################################################

TEMPLATE = app
TARGET = GUI
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += game.h
SOURCES += gui_main.cpp game.cpp
